require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/migrate/20170405074402_create_projects.rb'
    - 'db/migrate/20170406232832_create_users.rb'
    - 'db/migrate/20170407032233_create_skills.rb'
    - 'db/migrate/20170412181238_create_confirmations.rb'
    - 'db/migrate/20170417234130_rename_columns.rb'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  TargetRubyVersion: 2.3

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/AbcSize:
  Exclude:
    - 'app/lib/worknation/reputon.rb'

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/lib/worknation/reputon.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/lib/worknation/reputon.rb'

Performance/TimesMap:
  Exclude:
    - 'bin/deploy'
    - 'spec/factories.rb'

Rails:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

Style/AccessorMethodName:
  Exclude:
    - 'app/lib/worknation/reputon.rb'

Style/AlignParameters:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentationConsistency:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
