require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  TargetRubyVersion: 2.3

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/RequireParentheses:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - 'app/lib/decentral/*.rb'
    - 'db/migrate/*.rb'

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/lib/decentral/*.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/lib/decentral/*.rb'
    - 'db/migrate/*.rb'

Performance/TimesMap:
  Exclude:
    - 'bin/deploy'
    - 'spec/factories.rb'

Rails:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

Style/AccessorMethodName:
  Exclude:
    - 'app/lib/decentral/*.rb'

Style/AlignParameters:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/IndentationConsistency:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

# Don't turn this on, it's overzealous
Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
